### ISSUE TITLE
Can't fetch linked entities

### ISSUE THREAD

**Issue by Gounlaf** [api-platform/admin#35] opened 2017-08-04 21:43 UTC
Hi,

I'm facing a problem with, I guess, linked entities: I got the error "http://my.awesome.api[object Object] is not a valid URL." on Firefox / "Failed to execute 'fetch' on 'Window': Failed to parse URL from http://my.awesome.api[object Object]" on Chrome

* it happens both in **list** mode and in **view** mode: an indeterminate progress bar is still shown ('cause linked entities can't be retrieved, I guess)
* in **edit** mode, the field(s) corresponding to linked entities are not pre-filled; but I can fill the field(s) (a list of entities urls is shown); I didn't tried to save changes

With the console:
* I got only this: "Warning: Missing translation for key: "http://my.awesome.api[object Object] is not a valid URL."
* There are not network requests to see what URL has been called
* With the extension "React Developer Tools", I can see that the corresponding data (json) is attached to the cell where there is the indeterminate progress bar

Comparing to the **admin-on-rest** demo:
* my api data are returned with hydra context
* entities id are integer, like the demo
* property @id refer to the relative endpoint of entities

* Except the entry point and my webserver CORS configuration, I've not configured anything else for the admin parts
* Other lists of entities that don't have relations works correctly (right now, my doctrines entities relations are _Unidirectional_)

I will take a look to "reactjs" part... But it's totally new for me!

Thanks for your help,

Regards

**Comment by Gounlaf** [comment] 2017-08-04 22:42
* Version installed 0.1.8 correspond to commit 7860e253c040440d6f7f554513eba0cfde86d803 (don't know how npm registry works without git tags :x)
* both version 0.1.8 or last one in master have this bug
* Found that it's the parameter "id" called in the "fetchApi" methods that is... weird (https://github.com/api-platform/admin/blob/7860e253c040440d6f7f554513eba0cfde86d803/src/hydra/hydraClient.js#L128 or https://github.com/api-platform/admin/blob/38e7a77a5ad557124f5e28d3116a2c413252fd8c/src/hydra/hydraClient.js#L246); I can't debug the object to see what's in; it's nor string not numeric, so concatenation fail...

But I still don't know "what" call the **hydraClient** object

**Comment by Gounlaf** [comment] 2017-08-05 09:28
Good news: problem solved by upgrading admin-on-rest to version **^1.2**

**Comment by Arioch171** [comment] 2017-09-19 09:39
I have the exact same issue. Are your relations included via serialization groups? It looks like the HydraClient requires the relation data to be an URI instead of an hydrated object. This is why apiUrl+id returns `http://my.awesome.api[object Object]`.

**Comment by comxd** [comment] 2018-01-17 17:15
Hi @Arioch171 ,
Have you found a solution for that?

**Comment by marcinbis92** [comment] 2018-01-19 16:15
@comxd 
I have this same problem,
when I remove 'normalization_context' from attributes this fix it.

**Comment by Arioch171** [comment] 2018-01-22 10:59
@comxd The solution is basically what @marcinbis92 said. Do not use a default normalization_context which hydrates relations.

**Comment by comxd** [comment] 2018-01-22 12:04
Thanks, @Arioch171. 
This issue is a confirmed bug or it's a normal use case?

**Comment by Arioch171** [comment] 2018-01-25 11:00
@comxd I think it is a normal use case, but it should be documented that changing default normalization context messes with the admin.

**Comment by Simperfit** [comment] 2018-06-07 14:04
I think this has been fixed now. If not, please feel free to ping me

**Closed by Simperfit** 2018-06-07 14:04 UTC

**Comment by marcocesarato** [comment] 2020-06-16 07:08
I've the same issue with the current version version (2.2.1) when on list view or detail view there are some RelatedField they are requested by get request with [object-Object] instead of the id and they then are not returned correctly
