### ISSUE TITLE
Admin - invalid Semver

### ISSUE THREAD

**Issue by MarkLyck** [api-platform/admin#278] opened 2020-02-26 18:23 UTC
**API Platform version(s) affected**: 2.0.1

**Description**  
When running a barebones HydraAdmin with `parcel@next` it throws the following error:

```
Uncaught TypeError: Invalid Version: 
    at new SemVer (semver.js:324)
    at compare (semver.js:615)
    at Function.gte (semver.js:664)
    at Object.3dded889837ebff6240233adcb69db75.semver (index.js:9)
    at newRequire (test-app.ff4ae64a.js:68)
    at localRequire (test-app.ff4ae64a.js:80)
    at Object.c92c85298f9158dab8dda65e3e921945.tslib (parseHydraDocumentation.js:4)
    at newRequire (test-app.ff4ae64a.js:68)
    at localRequire (test-app.ff4ae64a.js:80)
    at Object.9808ff6dae1edf80d1f37d768219f002../fetchJsonLd (index.js:5)
```

**How to reproduce**  
Set up barebones hydra app with index.html and index.tsx

```
import React from "react";
import ReactDOM from "react-dom";
import { HydraAdmin } from "@api-platform/admin";
ReactDOM.render(<HydraAdmin />, document.getElementById("root"));
```

use parcel@2.x to run `parcel index.html`

I'm expecting this to run, but instead it fails with the above error.

**Comment by alanpoulain** [comment] 2020-05-30 15:02
Doesn't seem an API Platform Admin issue. Closing.

**Closed by alanpoulain** 2020-05-30 15:02 UTC

**Comment by MarkLyck** [comment] 2020-05-30 21:48
@alanpoulain It would be appreciated if you would at least try to reproduce the issue before closing.

This does not happen with solely react-admin. But a problem that's easily reproducible and only happens with api-platform.

**Comment by alanpoulain** [comment] 2020-05-31 09:19
Hello @MarkLyck.

It's not because the problem appears when you use this repository that the issue is coming from the code.
I know the code well and I could see it was not coming from it.

Being a maintainer on you free time means making compromises. I cannot debug and tests everything.

But I debugged it anyway. The issue is coming from here:
https://github.com/digitalbazaar/jsonld.js/blob/864284bef9f1d60f2e71004803f89ae8df0bc336/lib/index.js#L14
Probably because of how parcel works. The issue is then either on the `jsonld` repository or in the `parcel` repository.
