### ISSUE TITLE
Custom headers are not applied to the `ConstraintViolationList`

### ISSUE THREAD

**Issue by ahtohbi4** [api-platform/admin#191] opened 2019-07-17 14:10 UTC
Version: 0.6.2

I pass JWT token to a header with function `fetchHydra` (as [here](https://api-platform.com/docs/admin/authentication-support/) said) and it works correctly for requests to API. But for the request `ConstraintViolationList` this header is not passed.

<img width="626" alt="Снимок экрана 2019-07-17 в 17 05 48" src="https://user-images.githubusercontent.com/3686790/61382560-af978300-a8b5-11e9-8378-cd9718e01dca.png">

I found the place where this request is being made but I couldn't understand how it gets headers from `fetchHydra`.

<img width="612" alt="Снимок экрана 2019-07-17 в 16 53 50" src="https://user-images.githubusercontent.com/3686790/61382151-e4efa100-a8b4-11e9-9b54-67899d1003e3.png">

**Comment by mleczakm** [comment] 2019-10-24 14:20
We have also this problem, very annoying - I've just allow anonymous access for this endpoint because of this.

**Comment by pyrorules** [comment] 2019-11-08 09:16
Any news on this one?

**Comment by CampusFS** [comment] 2019-11-29 12:37
@mleczakm How did you achieve anonymous access for this endpoint ?

**Comment by Dogson** [comment] 2019-11-29 12:37
@mleczakm How did you manage to allow anonymous access for this endpoint ?

**Comment by mleczakm** [comment] 2019-11-29 12:45
> @mleczakm How did you manage to allow anonymous access for this endpoint ?
```
    access_control:
        ...
        # allow access to constraint violations list due to bug https://github.com/api-platform/admin/issues/191
        - { path: ^/api/contexts/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
       ...
```

**Comment by alanpoulain** [comment] 2020-05-30 15:18
I think it's now working as expected since `parseHydraDocumentation` can take an `Authorization` header. Closing but feel free to reopen if the issue is still here.

**Closed by alanpoulain** 2020-05-30 15:18 UTC
