### ISSUE TITLE
Unable to retrieve API documentation.

### ISSUE THREAD

**Issue by john-tau** [api-platform/admin#60] opened 2017-10-04 07:20 UTC
Hi I am having a issue.

I follow the steps below:

In my project folder
1. create-react-app my-admin
2. cd my-admin 
    yarn add @api-platform/admin
3. edit the src/App.js  by the way in the official website the https://api-platform.com/docs/admin/getting-started @api-platform-admin is incorrect you should update to @api-platform/admin
import React, { Component } from 'react';
import { HydraAdmin } from '@api-platform/admin';

class App extends Component {
  render() {
    return <HydraAdmin entrypoint="https://demo.api-platform.com"/> // Replace with your own API entrypoint
  }
}

export default App;

4. yarn start

5. it opens my google chrome and I get .... Unable to retrieve API documentation.

I use postman to retrieve https://demo.api-platform.com and I get the usual book and review objects... I get the same result if I use my local end-point. 

Can you please shed some light on this one... Maybe it is related to this project https://github.com/api-platform/api-platform-doc-parsing-check ?
Thanks

**Comment by mysiar** [comment] 2017-10-04 07:35
@john-tau 
Install this tool using npm https://github.com/api-platform/api-platform-doc-parsing-check 
as per https://www.npmjs.com/package/@api-platform/api-platform-doc-parsing-check/tutorial
Run this tool so you can see how to use it.
When you run in on your api and it passes and display all the endpoints it means that your api is parsable and can be used with API-Platform front tools without problem

**Comment by john-tau** [comment] 2017-10-04 09:39
@mysiar 
I was able to run the check tool on both  https://demo.api-platform.com and my local http://api.bookshop.dev/ api servers both gave the results below:

Checking documentation parsing for API @ https://demo.api-platform.com
[ 'books', 'reviews' ]
Number of endpoints parsed : 2

Checking documentation parsing for API @ http://api.bookshop.dev
[ 'books', 'reviews' ]
Number of endpoints parsed : 2

I still get the same issue so definitely not an issue on the api servers but something on the admin react code or maybe my dev environment which is on Windows 7 ...
  
![image](https://user-images.githubusercontent.com/25743430/31169247-ba63fdcc-a943-11e7-9e2e-5d14dba57f62.png)

![image](https://user-images.githubusercontent.com/25743430/31169346-0413dfbe-a944-11e7-9eff-a33b3d3a22df.png)

**Comment by mysiar** [comment] 2017-10-04 09:56
@john-tau check this entrypint
https://api-2.1.geomysiar.pl

**Comment by takeit** [comment] 2017-10-04 17:49
I have the same issue, https://demo.api-platform.com shows `Unable to retrieve API documentation` and  https://api-2.1.geomysiar.pl throws in console: 
```invariant.js:42 Uncaught Error: Element ref was specified as a string (listItem) but no owner was set. You may have multiple copies of React loaded```

**Comment by mysiar** [comment] 2017-10-04 17:51
The problem is in your app. 
I have running admin on https://api-2.1.geomysiar.pl

**Comment by takeit** [comment] 2017-10-04 18:02
I followed the documentation and installed the latest version. Which version are you running?

**Comment by alanpoulain** [comment] 2017-10-04 18:51
@takeit I have resolved this issue by forcing React 15.6 in package.json.

**Comment by dunglas** [comment] 2017-10-04 18:56
Did you noticed the last version of the doc? Just remove the react and react-dom packages from your package.json file and run yarn install.

**Comment by takeit** [comment] 2017-10-04 19:15
@dunglas thanks, it worked.

**Comment by soyuka** [comment] 2017-10-04 19:38
Closing, bump if needs reopening!

**Closed by soyuka** 2017-10-04 19:38 UTC

**Comment by john-tau** [comment] 2017-10-05 09:45
Thanks it works by removing the react and react-dom dependencies. You guys are awesome.
