### ISSUE TITLE
Edit/Show URLs use IRI instead of ID

### ISSUE THREAD

**Issue by DarthSomebody** [api-platform/admin#285] opened 2020-03-30 21:29 UTC
**API Platform version(s) affected**: latest

**Description**
The show-URLs for resources are not as expected `/{resource}/{id}/show`, but instead `/resource/{iri}/show`. The same applies to edit-URLs.

For example, I have the resource "tag" from the endpoint `/api/tags`. 
The IRI for the tag with the ID `1` is `/api/tags/1`.
The show-URL is `http://localhost:3000/tags//api/tags/1/show`.
It should be `http://localhost:3000/tags/1/show`.

**How to reproduce** 
```javascript
// Admin.js
import React from 'react';
import {HydraAdmin, ResourceGuesser, hydraDataProvider} from '@api-platform/admin';
import {createBrowserHistory} from "history";

const history = createBrowserHistory();
const data = hydraDataProvider("http://localhost:8000/api");

export default () => (
    <HydraAdmin dataProvider={data} history={history}>
        <ResourceGuesser name="tags"/>
    </HydraAdmin>
);
```

```javascript
// index.js
import React from 'react';
import ReactDOM from 'react-dom';
import Admin from "./Admin";

ReactDOM.render((
    <Admin/>
), document.getElementById('root'));
```

**Comment by alanpoulain** [comment] 2020-03-31 08:33
The admin is using the IRI not the ID.
Closing it because it's not a bug for me.
Feel free to reopen the issue if you think it really is.

**Closed by alanpoulain** 2020-03-31 08:33 UTC

**Comment by mleczakm** [comment] 2020-04-22 19:56
It is very bad UX, it should be at least possible to change this behavior without forking, especially if readme says it is "100% customizable".

**Comment by gstvg** [comment] 2020-04-30 10:00
Maybe is possible to use a proxy dataProvider that convert IRI to ID when reading, and ID to IRI back when writing. For resource id would be easy, but would get harder to find and translate IRI references inside a resource.
